name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  mobile_scanner: ^5.2.3
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  provider: ^6.0.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SpaceAge
      fonts:
        - asset: lib/custom_fonts/space_age.ttf