name: scanselmi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  mobile_scanner: ^5.2.3
  dio: ^5.0.10
  path_provider: ^2.0.15
  permission_handler: 11.3.1
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
